# Generated by Django 2.2.7 on 2019-11-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDegree',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('degree', models.CharField(db_column='escolaridade', max_length=30, verbose_name='escolaridade')),
            ],
            options={
                'verbose_name': 'grau mínimo exigido',
                'db_table': 'grau_minimo',
            },
        ),
        migrations.CreateModel(
            name='SalaryRange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value1', models.DecimalField(db_column='valor_base', decimal_places=2, max_digits=5, verbose_name='valor base da faixa')),
                ('value2', models.DecimalField(db_column='valor_teto', decimal_places=2, max_digits=8, verbose_name='valor teto da faixa')),
            ],
            options={
                'verbose_name': 'faixa salarial',
                'db_table': 'faixa_salarial',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_column='nome_vaga', max_length=150, verbose_name='nome da vaga')),
                ('requirements', models.TextField(db_column='requisitos', verbose_name='requisitos')),
                ('required_degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.RequiredDegree')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.SalaryRange')),
            ],
            options={
                'verbose_name': 'vagas',
                'db_table': 'vagas',
            },
        ),
    ]
