# Generated by Django 2.2.7 on 2019-12-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='candidates',
            field=models.ManyToManyField(blank=True, through='opportunities.CandidatesJobsApply', to='users.Candidate'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='required_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.RequiredDegree', verbose_name='Grau exigido'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.SalaryRange', verbose_name='Faixa salarial'),
        ),
        migrations.AddField(
            model_name='candidatesjobsapply',
            name='candidate',
            field=models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.PROTECT, to='users.Candidate', verbose_name='candidato'),
        ),
        migrations.AddField(
            model_name='candidatesjobsapply',
            name='job',
            field=models.ForeignKey(db_column='oportunidade_id', on_delete=django.db.models.deletion.PROTECT, to='opportunities.Jobs', verbose_name='oportunidade'),
        ),
    ]
